project:
  type: website
  output-dir: _site

website:
  title: ""
  favicon: "image/badger.png"
  navbar:
    logo: "image/badger.png"
    right:
      - icon: github
        href: https://github.com/xrander
      - icon: twitter
        href: https://x.com/fp_talk
    left: 
      - blog.qmd
format:
  html:
    theme: darkly
    css: styles.css

