project:
  type: website
  output-dir: _site

website:
  title: ""
  favicon: "image/badger.png"
  navbar:
    logo: "image/badger.png"
    right:
      - icon: github
        href: https://github.com/xrander
      - icon: twitter
        href: https://x.com/fp_talk
      - icon: linkedin
        href: https://www.linkedin.com/in/olamide-adu
    left: 
      - blog.qmd
      - icon: house-fill
        href: https://olamideadu.com
format:
  html:
    theme: darkly
    css: styles.css
code-fold: false

