name: Install Dependencies

on:
  workflow_run:
    workflows: ["Quarto Blog Auto-Render and Deploy"]
    types: [completed]

jobs:
  install-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
            
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gsfonts \
            libcurl4-openssl-dev \
            libmagick++-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            imagemagick \
            libmagickcore-6.q16-6-extra \
            libfreetype6-dev \
            libmagickwand-dev \
            libglpk-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Restore renv cache
        uses: actions/cache@v4
        with:
          path: renv/library
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Restore R environment with renv
        run: |
          Rscript -e "
          install.packages('magick', type = 'source');
          setRepositories(ind=1:2);
          install.packages('ggimage');
          install.packages('renv');
          renv::restore();
          "



      - name: Create virtualenv + install Python packages
        run: |
          Rscript -e "
            library(reticulate);
            virtualenv_create('r-reticulate', python = 'python3.10');
            use_virtualenv('r-reticulate', required = TRUE);
            py_install('requirements.txt', pip = TRUE)
          "
