name: Install Dependencies

on:
  workflow_run:
    workflows: ["Quarto Blog Auto-Render and Deploy"]
    types: [completed]

jobs:
  install-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gsfonts \
            libcurl4-openssl-dev \
            libmagick++-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            imagemagick \
            libmagickcore-6.q16-6-extra \
            libfreetype6-dev \
            libmagickwand-dev \
            libglpk-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Restore renv cache
        uses: actions/cache@v4
        with:
          path: renv/library
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Restore R environment with renv
        run: |
          Rscript -e "
          install.packages('magick', type = 'source');
          setRepositories(ind=1:2);
          install.packages('ggimage');
          install.packages('renv');
          renv::restore();
          "

      - name: Set up pyenv and Python
        run: |
          curl https://pyenv.run | bash
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv install 3.11.9
          pyenv virtualenv 3.11.9 r-reticulate-env
          pyenv global 3.11.9/envs/r-reticulate-env
          echo "Python version:"
          python --version

      - name: Use Python in R via reticulate
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          Rscript -e "
            library(reticulate);
            use_virtualenv(Sys.getenv('PYENV_ROOT') %+% '/versions/3.11.9/envs/r-reticulate-env', required = TRUE);
            py_install('requirements.txt', pip = TRUE);
          "
