name: Quarto Blog Auto-Render and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: main
  
  workflow_dispatch:
  schedule:
    - cron: "0 08 * * *"

  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.BLOG_TOKEN }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_BLOG_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BLOG_ID }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Cache R packages
        uses: actions/cache@v3
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.5.57"
          # LaTeX installation
          tinytex: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
      
      - name: Render Blog
        run: quarto render

      - name: Commit and push changes
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './_site'
          production-branch: main
          github-token: ${{ secrets.BLOG_TOKEN }}
          deploy_message:
            "Automated blog render"
          enable-pull-request-comment: false
          enable-commit-comment: false