name: Quarto Blog Auto-Render and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches: master
  
  workflow_dispatch:
  schedule:
    - cron: "0 08 * * *"

  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.BLOG_TOKEN }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_BLOG_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BLOG_ID }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Cache system dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.5.57"
          # LaTeX installation
          tinytex: true
      
      - name: Cache Quarto
        uses: actions/cache@v4
        with:
          path: ~/.quarto
          key: ${{ runner.os }}-quarto-${{ hashFiles('**/*.qmd', '**/*.ipynb') }}
          restore-keys: |
            ${{ runner.os }}-quarto-
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION', '**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-
      
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'
      
      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install venv
          python -m pip install -r requirements.txt
      
      - name: Cache Quarto render output
        uses: actions/cache@v4
        with:
          path: |
            .quarto
            _site
          key: ${{ runner.os }}-render-${{ hashFiles('**/*.qmd', '**/*.ipynb', '**/*.py', '**/*.R') }}
          restore-keys: |
            ${{ runner.os }}-render-
        
      - name: Render Blog
        run: quarto render
      
      - name: Deploy to Netlify
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './_site'
          production-branch: master
          github-token: ${{ secrets.BLOG_TOKEN }}
          deploy-message: "Automated blog render - ${{ github.sha }}"
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_BLOG_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BLOG_ID }}