name: Render Blog

on:
  workflow_run:
    workflows: ["Install Dependencies"]
    types: [completed]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.5.57"
          tinytex: true

      - name: Render the blog
        run: |
          Rscript -e "library(reticulate); use_virtualenv('r-reticulate', required = TRUE)"
          quarto render
