name: Setup Blog Environment and Quarto

on:
  workflow_dispatch:
  push:
    branches: [master]
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.BLOG_TOKEN }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_BLOG_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BLOG_ID }}
      
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Cache system dependencies
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-packages.txt') }}
          restore-keys: ${{ runner.os }}-apt-

      - name: Install system dependencies
        runs: |
          sudo apt-get update
          sudo apt-get install -y librcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "latest"
          tinytex: false
          
      - name: Cache Quarto Install
        uses: actions/cache@v4
        with:
          path: ~/.quarto
          key: ${{ runner.os }}-quarto-${{ hashFiles('**/*.qmd', '**/*.ipynb', '_quarto.yml') }}
          restore-keys: ${{ runner.os }}-quarto-